version: '3.8'

services:
  app:
    image: 'app/java'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/application
      - SPRING_DATASOURCE_USERNAME=user_application
      - SPRING_DATASOURCE_PASSWORD=application
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA=locadora
    ports:
      - "8080:8080"
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user_application
      POSTGRES_PASSWORD: application
      POSTGRES_DB: application
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080